version: "3.9"
services:
  app:
    build: .
    restart: always
    container_name: django
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resivalex.rule=Host(`resivalex.com`)"
      - "traefik.http.routers.resivalex.entrypoints=https"
      - "traefik.http.routers.resivalex.tls.certresolver=myresolver"
      - "traefik.http.services.resivalex.loadbalancer.server.port=8000"
    networks:
      - web
networks:
  web:
    external: true
