version: "3.9"
services:
  resivalex:
    build: .
    restart: always
    container_name: resivalex
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    volumes:
      - .:/app
    networks:
      - web

networks:
  web:
    external: true
